/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FadingComponent.java
 *
 * Created on Aug 22, 2012, 11:58:49 PM
 */
package com.wavesoft.webng.components;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author icharala
 */
public class FadingComponent extends javax.swing.JPanel implements ComponentListener {

    BufferedImage biFront, biBack;
    
    /** Creates new form FadingComponent */
    public FadingComponent() {
        initComponents();
        resetBuffers();
        addComponentListener(this);
    }
    
    private void resetBuffers() {
        biFront = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_ARGB);
        biBack = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_ARGB);
    }

    @Override
    public void paint(Graphics grphcs) {
        if (biFront == null) return;
        super.paint(biFront.getGraphics());
        
        Graphics2D g2d = (Graphics2D) grphcs;
        g2d.setComposite(AlphaComposite.getInstance(
             AlphaComposite.SRC_OVER, 0.2f));
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);

        g2d.drawImage(biFront, 0, 0, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 52, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 37, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent ce) {
        resetBuffers();
    }

    @Override
    public void componentMoved(ComponentEvent ce) {
    }

    @Override
    public void componentShown(ComponentEvent ce) {
    }

    @Override
    public void componentHidden(ComponentEvent ce) {
    }
}
