/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WideButton.java
 *
 * Created on Jul 19, 2012, 4:14:24 PM
 */
package com.wavesoft.webng.components;

import javax.swing.Icon;

/**
 *
 * @author icharala
 */
public class WideButton extends javax.swing.JPanel {

    private Icon icon = null;
    
    public void setIcon(Icon icon) {
        this.icon = icon;
        repaint();
    }
    
    public Icon getIcon() {
        return this.icon;
    }

    /** Creates new form WideButton */
    public WideButton() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 182, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 140, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
